pipeline {
    
    agent any
	environment {
		GITHUB_PACKAGE_TOKEN = credentials("DanyToken")
	}		
	
	triggers {
        githubPush()
    }
    
    stages {
        stage ('Init') {
            steps {
                echo 'Initializing...'
            }
        }

	stage ('Create docker image'){
		steps {
			dir('creditCard'){
				sh 'docker build -t tailorw/fin-credit-card:dev --build-arg PACKAGE_TOKEN=$GITHUB_PACKAGE_TOKEN .'
				withDockerRegistry(credentialsId: 'Tailorw-DockerCredentials', url: "") {
                			sh 'docker push tailorw/fin-credit-card:dev'
                		}
			}
		}
	}

	stage ('Publish to Kubernetes') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'KubernetesCredential', namespace: 'finamer', restrictKubeConfigAccess: false, serverUrl: 'https://172.20.41.100:5443') {
                    sh 'kubectl apply -f kubernetes-config/deployments/creditCard.yaml'
                }
            }
        }
    }
}
