version: '3.8'
services:
  db:
    container_name: db
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5431:5432"
    expose:
      - 5431
    networks:
      - microservices-net

  registry-service:
    build:
      context: ./registry
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  config-service:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-net
    depends_on:
      - registry-service

  treatments-service:
    build:
      context: ./treatments
      dockerfile: Dockerfile
    ports:
      - "9906:9906"
    environment:
      RC_SERVER_CONFIG: host.docker.internal
      RC_ACTIVE_PROFILE: dev
      KAFKA_BOOTSTRAP_ADDRESS: host.docker.internal:29092
    networks:
      - microservices-net

  calendar-service:
    build:
      context: ./calendar
      dockerfile: Dockerfile
    ports:
      - "9908:9908"
    environment:
      RC_SERVER_CONFIG: host.docker.internal
      RC_ACTIVE_PROFILE: dev
      KAFKA_BOOTSTRAP_ADDRESS: host.docker.internal:29092
    networks:
      - microservices-net

  patients-service:
    build:
      context: ./patients
      dockerfile: Dockerfile
    ports:
      - "9909:9909"
    environment:
      RC_SERVER_CONFIG: host.docker.internal
      RC_ACTIVE_PROFILE: dev
      KAFKA_BOOTSTRAP_ADDRESS: host.docker.internal:29092
    networks:
      - microservices-net

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      RC_SERVER_CONFIG: host.docker.internal
      RC_ACTIVE_PROFILE: dev
      KAFKA_BOOTSTRAP_ADDRESS: host.docker.internal:29092
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - microservices-net
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 127.0.0.1:6379:6379

networks:
  microservices-net:
    driver: bridge
