pipeline {
    
    agent any
    
	triggers {
        githubPush()
    }
    
    stages {
        stage ('Init') {
            steps {
                echo 'Initializing..'
            }
        }
    }
}
