package com.kynsoft.finamer.settings.application.command.replicate.objects;

public enum ObjectEnum {
    MANAGE_INVOICE_TYPE,
    MANAGE_INVOICE_STATUS,
    MANAGE_INVOICE_TRANSACTION_TYPE,
    MANAGE_PAYMENT_STATUS,
    MANAGE_PAYMENT_SOURCE,
    MANAGE_PAYMENT_TRANSACTION_TYPE,
    MANAGE_ATTACHMENT_TYPE,

    MANAGE_AGENCY_TYPE,
    MANAGE_AGENCY,
    MANAGE_BANK_ACCOUNT,
    MANAGE_EMPLOYEE,
    MANAGE_HOTEL,
    MANAGE_ATTACHMENT_STATUS,
    MANEGE_CLIENT
}
