apiVersion: v1
kind: Secret
metadata:
  name: cloudbridges-secret
  namespace: finamer
type: Opaque
data:
  RC_ACTIVE_PROFILE: ZGV2
  RC_SERVER_CONFIG: Y29uZmlnLXNlcnZpY2U=
  SERVER_PORT: OTkwOQ==
  DB_HOST_RW: amRiYzpwb3N0Z3Jlc3FsOi8vemV1cy1ydy5wb3N0Z3Jlcy1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZmluYW1lci1jbG91ZGJyaWRnZXM=
  DB_HOST_R: amRiYzpwb3N0Z3Jlc3FsOi8vemV1cy1yby5wb3N0Z3Jlcy1wcm9kLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZmluYW1lci1jbG91ZGJyaWRnZXM=
  DB_USER_RW: ZmluYW1lcl9ydw==
  DB_USER_R: ZmluYW1lcl9ybw==
  DB_PASSWORD_RO: RENNaHB6T0lDYnVVeGlVU1owNDRtaFdTSFUxUjJVNTNJRHdPeUpMUnV3VTFyOUo3NGxJVHA=
  DB_PASSWORD_RW: NUczMHkxY1h6ODljQTF5YzBnQ0UzT2hoQkxRa3ZVVFYyaWNxejVxTlJRR3E0Y2JNNUYwYmM=
  REDIS_ADDRESS: cmVkaXMtc2VydmljZS5jYWNoZS5zdmMuY2x1c3Rlci5sb2NhbA==
  REDIS_PORT: NjM3OQ==
  KAFKA_BOOTSTRAP_ADDRESS: a2Fma2Eua2Fma2Euc3ZjLmNsdXN0ZXIubG9jYWw6OTA5Mg==
  KAFKA_GROUP_ID: Q0xPVURCUklER0VT
  AWS_ACCESS_SECRET: MzQ0MjljMWIwY2FjNWQ4YTM4YTk1N2FiY2U4ZDk3MmQwOWY3YzBhZWYxODZhMGFlZjdmYzhhNzg1ZDZlNTQ3OA==
  AWS_ACCESS_KEY: YjUzM2M0ZDdiM2UxMWMyY2JiZDZmMzEyMzhkYjdjYTk=
  MAILJET_KEY: NWUyMDFkM2JlMzk4Y2EwOTkwZTM0ZjkzODU5YjcxOWU=
  MAILJET_SECRET: YWNkMjc4ZDg3ZTUwNjVmYmRjNTAxNzliMDczNjMyODg=
