pipeline {
    
    agent any
    
	triggers {
        githubPush()
    }
    
    stages {
        stage ('Init') {
            steps {
                echo 'Initializing...'
            }
        }

	stage ('Create docker image'){
		steps {
			dir('config'){
				sh 'docker build -t tailorw/fin-config:dev .'
				withDockerRegistry(credentialsId: 'Tailorw-DockerCredentials', url: "") {
                			sh 'docker push tailorw/fin-config:dev'
                		}
			}
		}
	}

	stage ('Publish to Kubernetes') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'KubernetesCredential', namespace: 'finamer', restrictKubeConfigAccess: false, serverUrl: 'https://172.20.41.100:5443') {
                    sh 'kubectl apply -f kubernetes-config/deployments/config.yaml'
                }
            }
        }
    }
}
