@Library('emailNotification') _
import com.tailorwsas.notificaciones.NotificadorEmail

pipeline {
    
    agent any

    environment {
        SISTEMA = 'ERP'
        SRC = 'finamer-admin'
        ORIGIN_BRANCH_NAME = "${env.GIT_BRANCH}"
        DOCKER_IMAGE_NAME = 'tailorw/erp-admin:version'
        DOCKER_CREDENTIALS = 'Tailorw-DockerCredentials'
        NAMESPACE = 'finamer'
        K3S_CREDENTIALS = 'KubernetesCredential-env'
        YAML = 'finamer-admin'
        DEPLOYMENT_NAME = 'finamer-admin'
        URL_DEV = credentials("URL-K3S-dev")
        URL_QA = credentials("URL-K3S-qa")
	EMAIL_FROM = "${env.CORREO_ORIGEN}"
        ESTADO_OK = 'OK'
        ESTADO_ERROR = 'ERROR'
    }
    
    triggers {
        githubPush()
    }
    
    stages {

        stage ('Init') {
            steps {
                echo 'Initializing......'
                script {   
                    def branch = env.ORIGIN_BRANCH_NAME.replace('origin/', '')
                    env.BRANCH_NAME = branch

                    def dockerImage = env.DOCKER_IMAGE_NAME.replace('version', env.BRANCH_NAME)
                    env.DOCKER_IMAGE = dockerImage

                    def k3sCredentials = env.K3S_CREDENTIALS.replace('env', env.BRANCH_NAME)
                    env.SERVER_K3S_CREDENTIALS = k3sCredentials

                    if(env.BRANCH_NAME == 'dev'){
                        env.SERVER_K3S_URL = env.URL_DEV
                        env.EMAIL_LIST = env.EMAIL_LIST_DEV_ERP_FRONTEND
                    }
                    if(env.BRANCH_NAME == 'qa'){
                        env.SERVER_K3S_URL = env.URL_QA
                        env.EMAIL_LIST = env.EMAIL_LIST_QA
                    }
                }
            }
        }

        stage ('Create docker image'){
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
                withDockerRegistry(credentialsId: "${DOCKER_CREDENTIALS}", url: "") {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage ('Publish to Kubernetes') {
            steps {
                withKubeConfig(credentialsId: "${SERVER_K3S_CREDENTIALS}", namespace: "${NAMESPACE}", restrictKubeConfigAccess: false, serverUrl: "${SERVER_K3S_URL}") {
                    //sh 'kubectl apply -f $YAML'
                    sh 'kubectl rollout restart deploy $DEPLOYMENT_NAME'
                }
            }
        }
    }
	
	post {
        success {
            script {
                def notificator = new NotificadorEmail(this)
                notificator.sendEmail(env.EMAIL_LIST, env.EMAIL_FROM, env.SRC, env.SISTEMA, env.BRANCH_NAME, env.ESTADO_OK)
            }
        }
        failure {
            script {
                def notificator = new NotificadorEmail(this)
                notificator.sendEmail(env.EMAIL_LIST, env.EMAIL_FROM, env.SRC, env.SISTEMA, env.BRANCH_NAME, env.ESTADO_ERROR)
            }
        }
    }
}
