pipeline {
    
    agent any

	environment {
		GIT_PACKAGE_TOKEN = credentials("GithubPackageToken")
		BRANCH_NAME = "${env.GIT_BRANCH}"
	}
	
	triggers {
        githubPush()
    }
    
    stages {
        stage ('Init') {
            steps {
                echo 'Initializing......'
            }
        }

	stage ('Create docker image'){
		steps {
			dir('cloudBridges'){
				sh 'docker build -t tailorw/fin-cloud-bridges:dev --build-arg PACKAGE_TOKEN=$GIT_PACKAGE_TOKEN --build=arg POM_NAME=pom-${env.GIT_BRANCH}.xml.'
				withDockerRegistry(credentialsId: 'Tailorw-DockerCredentials', url: "") {
                			sh 'docker push tailorw/fin-cloud-bridges:dev'
                		}
			}
		}
	}

	stage ('Publish to Kubernetes') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'KubernetesCredential', namespace: 'finamer', restrictKubeConfigAccess: false, serverUrl: 'https://172.20.41.150:5443') {
                    sh 'kubectl apply -f kubernetes-config/deployments/cloudbridges.yaml'
                }
            }
        }
    }
}
