pipeline {
    
    agent any
    
	triggers {
        githubPush()
    }
    
    stages {
        stage ('Init') {
            steps {
                echo 'Initializing......'
            }
        }

	stage ('Create docker image'){
		steps {
			dir('cloudBridges'){
				sh 'docker build -t tailorw/fin-cloud-bridges:dev .'
				withDockerRegistry(credentialsId: 'Tailorw-DockerCredentials', url: "") {
                			sh 'docker push tailorw/fin-cloud-bridges:dev'
                		}
			}
		}
	}

	stage ('Publish to Kubernetes') {
            steps {
                withKubeConfig(caCertificate: '', clusterName: '', contextName: '', credentialsId: 'KubernetesCredential', namespace: 'finamer', restrictKubeConfigAccess: false, serverUrl: 'https://172.20.41.100:5443') {
                    sh 'kubectl apply -f https://raw.githubusercontent.com/tailorwr/repository/main/finamer/dev/app/yaml/deployments/cloudbridges.yaml?token=GHSAT0AAAAAACUG33WXQC4YUZK3APLTHZUQZUIOQZQ'
                }
            }
        }
    }
}
